version: '2'
services:

  zenops-mysql:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/zenops-mysql:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=P2ssw0rd
    ports:
      - "53306:3306"

  zenops-pms:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/zenops-pms:1.0
    depends_on:
      - zenops-mysql
    ports:
      - "50080:80"
    tty: true
    stdin_open: true
    command: sh /z/scripts/launch-pms.sh

  zenops-gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:58080'
        # gitlab.rb configuration here, each on its own line
    ports:
      - '58080:58080'
      - '50022:22'
    volumes:
      - '$ZENOPS_HOME/gitlab/config:/etc/gitlab'
      - '$ZENOPS_HOME/gitlab/logs:/var/log/gitlab'
      - '$ZENOPS_HOME/gitlab/data:/var/opt/gitlab'
      - '$ZENOPS_HOME/gitlab/letsencrypt:/letsencrypt'
